# Generated by Django 3.1.6 on 2021-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_test', '0003_auto_20210218_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='correct',
            field=models.TextField(blank=True, help_text='FieldPanel viðmót', null=True),
        ),
    ]
