# Generated by Django 4.0.10 on 2025-03-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_basetemplate_contributioncallout_contributionsettings_generalsitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionsettings',
            name='callout_snippet',
        ),
        migrations.RemoveField(
            model_name='contributionsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='generalsitesettings',
            name='base_template',
        ),
        migrations.RemoveField(
            model_name='generalsitesettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='BaseTemplate',
        ),
        migrations.DeleteModel(
            name='ContributionCallout',
        ),
        migrations.DeleteModel(
            name='ContributionSettings',
        ),
        migrations.DeleteModel(
            name='GeneralSiteSettings',
        ),
    ]
