# Generated by Django 4.0.10 on 2025-03-04 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0004_remove_contributionsettings_callout_snippet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionCallout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.RichTextField()),
                ('cta_copy', models.CharField(blank=True, max_length=255)),
                ('views_per_week', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_dir', models.CharField(blank=True, max_length=255)),
                ('head_js', models.TextField(blank=True, null=True)),
                ('google_analytics_property', models.CharField(blank=True, max_length=255)),
                ('base_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.basetemplate')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callout_active', models.BooleanField(default=False, verbose_name='Kveikt á styrktarbeiðni í greinum')),
                ('callout_snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.contributioncallout', verbose_name='Efni til að birta neðst í greinum')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Styrkir',
            },
        ),
    ]
