# Generated by Django 3.1.4 on 2021-08-14 00:37

import articles.models
from django.db import migrations, models
import django.db.models.deletion
import home.mixins
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author_name_override', models.CharField(blank=True, max_length=255, null=True)),
                ('author_show_as_large', models.BooleanField(default=False)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('styles_override', models.TextField(blank=True, null=True)),
                ('additional_js', models.TextField(blank=True, null=True)),
                ('extra_title', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(editor='draftail', template='kjarninn/articles/block_templates/paragraph_block.html')), ('html', wagtail.core.blocks.RawHTMLBlock(template='kjarninn/articles/block_templates/html_block.html'))])),
                ('header_image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('editors_notes', models.TextField(blank=True, help_text='<br> býr til nýja línu. <i>...</i> skáletrar. <b>...</b> feitletrar.', null=True)),
                ('note_date', models.DateField(blank=True, help_text='Dagsetning athugasemdar. Valkvætt.', max_length=255, null=True)),
                ('related_links_title', models.CharField(blank=True, help_text='Shortcode: [links]', max_length=80, null=True)),
                ('sub_article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_article', wagtail.core.fields.RichTextField(blank=True, help_text='Shortcode: [box] — <p> skilgreinir meginmál.')),
                ('sub_article_layout', models.CharField(choices=[('none', 'Fela hliðarefni'), ('half', 'Einn dálkur'), ('full', 'Tveir dálkar')], default='none', max_length=255, null=True)),
                ('header_image_crop', models.BooleanField(default=False, help_text='Viltu láta myndskurð ráðast af fókus svæði?')),
                ('header_image_layout', models.CharField(choices=[('default', 'Sjálfval'), ('landscape', 'Mynd á breiddina'), ('portrait', 'Mynd á hæðina'), ('video', 'Birta myndband'), ('noimg', 'Fela mynd')], default='default', help_text='Veldu myndastillingu á aðalmynd. Hefur aðeins áhrif á þessari síðu.', max_length=225)),
                ('header_video', models.CharField(blank=True, help_text='Slóð á myndbönd frá YouTube og Vimeo.', max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(home.mixins.SiteSettingsTemplateMixin, articles.models.MovePagesMixin, 'wagtailcore.page', articles.models.ArticleTagStuffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='English title')),
                ('backend_title', models.CharField(max_length=255, null=True, verbose_name='Bakendatitill')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('color', models.CharField(default='#000000', max_length=255)),
                ('list_cluster', models.IntegerField(default=99, help_text='Vinsamlegast notið tölur 0-99', verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['list_cluster', 'backend_title', 'title'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='TagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('twitter_user', models.SlugField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('list_cluster', models.IntegerField(default=99, help_text='Vinsamlegast notið tölur 0-99', verbose_name='Ordering')),
                ('facebook_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Höfundur',
                'verbose_name_plural': 'Höfundar',
                'ordering': ['list_cluster', 'title'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_articletag_taggeditems', to='articles.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_articletag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlePageRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='articles.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.author'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='author_image_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.category'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_related_page', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='articles.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
